neighbouring_cell_configuration =
(
 {
   physCellId = 1;
   absoluteFrequencySSB = 641280;
   dl_frequencyBand = 78;
   nr_cellid = 12345679;
 },
 {
   physCellId = 0;
   absoluteFrequencySSB = 641280;
   dl_frequencyBand = 78;
   nr_cellid = 12345678;
 }
);
