global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:

  ###################################################
  # Prometheus
  ###################################################
  - job_name: "prometheus"

    static_configs:
      - targets:
          - localhost:9095

        labels:
          app: prometheus
          plmn: HPLMN

  ###################################################
  # AMF
  ###################################################
  - job_name: "amf"

    static_configs:
      - targets:
          - 127.0.1.5:9090

        labels:
          nf: AMF
          plmn: HPLMN

  ###################################################
  # SMF
  ###################################################
  - job_name: "smf"

    static_configs:
      - targets:
          - 127.0.1.4:9090

        labels:
          nf: SMF
          plmn: HPLMN

  ###################################################
  # UPF
  ###################################################
  - job_name: "upf"

    static_configs:
      - targets:
          - 127.0.1.7:9090

        labels:
          nf: UPF
          plmn: HPLMN


  ###################################################
  # PCF
  ###################################################
  - job_name: "pcf"

    static_configs:
      - targets:
          - 127.0.1.13:9090

        labels:
          nf: PCF
          plmn: HPLMN
